"""Tests for the pre-print check in print_send.py.

The rule these encode: before a print starts, what the G-code was sliced for and
what the machine actually has loaded must agree. Getting this wrong is not a
software error that shows up in a log — it is a 40-minute print of PETG settings
into PLA, or 0.4 mm extrusions through a 0.6 mm nozzle. The checks read the
G-code header rather than slicer-config.json on purpose: the file is what the
printer executes, and it may have been sliced with a config that has since
changed, or on another machine entirely.

The other half of the rule is that "could not verify" must never be reported as
"matches" — several tests below exist only to pin that distinction.
"""

import os
import sys
import tempfile
import unittest

import helpers  # noqa: F401

sys.path.insert(0, helpers.ADDON_DIR)
import print_send  # noqa: E402

# Trimmed from a real OrcaSlicer 2.4.2 file for the Prusa CORE One: the config
# block sits at the END of the file, which is why gcode_settings reads the tail
# as well as the head.
HEADER = "\n".join([
    "; generated by OrcaSlicer 2.4.2 on 2026-07-24",
    ";TYPE:Custom",
    "M73 P0 R39",
    "G90",
])
FOOTER = "\n".join([
    "; filament used [g] = 1.32",
    "; nozzle_diameter = 0.4",
    "; filament_type = PLA",
    "; printer_model = Prusa CORE One",
    "; nozzle_temperature = 220",
])


def write_gcode(head=HEADER, foot=FOOTER, filler=0):
    handle = tempfile.NamedTemporaryFile(
        "w", suffix=".gcode", delete=False, encoding="utf-8")
    handle.write(head + "\n")
    if filler:
        handle.write(("G1 X10 Y10 E0.5\n" * filler))
    handle.write(foot + "\n")
    handle.close()
    return handle.name


class GcodeSettingsTests(unittest.TestCase):
    def setUp(self):
        self.paths = []

    def tearDown(self):
        for path in self.paths:
            os.unlink(path)

    def make(self, **kwargs):
        path = write_gcode(**kwargs)
        self.paths.append(path)
        return path

    def test_reads_settings_from_the_footer(self):
        found = print_send.gcode_settings(self.make())
        self.assertEqual(found["nozzle_diameter"], "0.4")
        self.assertEqual(found["filament_type"], "PLA")
        self.assertEqual(found["printer_model"], "Prusa CORE One")

    def test_finds_the_footer_across_a_large_file(self):
        # A real print is megabytes of motion between the header and the config
        # block. Reading only the first 64 KB would miss every setting.
        path = self.make(filler=200000)
        self.assertGreater(os.path.getsize(path), print_send.GCODE_HEADER_BYTES * 2)
        found = print_send.gcode_settings(path)
        self.assertEqual(found["filament_type"], "PLA")

    def test_reads_settings_from_the_header_too(self):
        # PrusaSlicer puts some keys up top; both ends must be searched.
        found = print_send.gcode_settings(
            self.make(head="; nozzle_diameter = 0.6\n" + HEADER, foot="; end\n"))
        self.assertEqual(found["nozzle_diameter"], "0.6")

    def test_missing_keys_are_absent_not_guessed(self):
        found = print_send.gcode_settings(self.make(head="G90\n", foot="; done\n"))
        self.assertNotIn("nozzle_diameter", found)
        self.assertNotIn("filament_type", found)

    def test_unreadable_file_is_a_setup_error(self):
        with self.assertRaises(print_send.SetupError):
            print_send.gcode_settings("/nonexistent/never.gcode")


class PreflightMismatchTests(unittest.TestCase):
    SLICED = {"nozzle_diameter": "0.4", "filament_type": "PLA"}

    def test_agreement_produces_no_problems(self):
        problems, unknown = print_send.preflight_mismatches(
            self.SLICED, {"nozzle_diameter": 0.4, "material": "PLA"})
        self.assertEqual(problems, [])
        self.assertEqual(unknown, [])

    def test_material_comparison_ignores_case(self):
        problems, unknown = print_send.preflight_mismatches(
            {"filament_type": "pla"}, {"material": "PLA"})
        self.assertEqual(problems, [])

    def test_wrong_nozzle_is_a_problem(self):
        problems, _ = print_send.preflight_mismatches(
            self.SLICED, {"nozzle_diameter": 0.6, "material": "PLA"})
        self.assertEqual(len(problems), 1)
        self.assertIn("nozzle", problems[0])
        self.assertIn("0.6", problems[0])

    def test_wrong_filament_is_a_problem(self):
        problems, _ = print_send.preflight_mismatches(
            self.SLICED, {"nozzle_diameter": 0.4, "material": "PETG"})
        self.assertEqual(len(problems), 1)
        self.assertIn("filament", problems[0])

    def test_both_wrong_are_reported_together(self):
        problems, _ = print_send.preflight_mismatches(
            self.SLICED, {"nozzle_diameter": 0.6, "material": "PETG"})
        self.assertEqual(len(problems), 2)

    def test_float_string_nozzle_compares_numerically(self):
        # "0.40" and 0.4 are the same nozzle; a string comparison would cry wolf.
        problems, _ = print_send.preflight_mismatches(
            {"nozzle_diameter": "0.40"}, {"nozzle_diameter": 0.4})
        self.assertEqual(problems, [])

    def test_silent_printer_is_unverified_not_approved(self):
        problems, unknown = print_send.preflight_mismatches(self.SLICED, {})
        self.assertEqual(problems, [])
        self.assertEqual(len(unknown), 2)

    def test_empty_spool_reading_is_unverified(self):
        for empty in ("", "---", "unknown", "none"):
            problems, unknown = print_send.preflight_mismatches(
                self.SLICED, {"nozzle_diameter": 0.4, "material": empty})
            self.assertEqual(problems, [], empty)
            self.assertEqual(len(unknown), 1, empty)

    def test_gcode_without_settings_is_unverified(self):
        problems, unknown = print_send.preflight_mismatches(
            {}, {"nozzle_diameter": 0.4, "material": "PLA"})
        self.assertEqual(problems, [])
        self.assertEqual(len(unknown), 2)


class PrinterActualTests(unittest.TestCase):
    """printer_actual must never invent a value it did not receive."""

    def setUp(self):
        self.real_http = print_send._http
        self.real_key = print_send.resolve_api_key
        print_send.resolve_api_key = lambda network: "key"

    def tearDown(self):
        print_send._http = self.real_http
        print_send.resolve_api_key = self.real_key

    def fake_http(self, responses):
        def _http(request):
            for suffix, (status, body) in responses.items():
                if request.full_url.endswith(suffix):
                    return status, body.encode("utf-8")
            return 404, b"{}"
        print_send._http = _http

    def test_reads_nozzle_and_material(self):
        self.fake_http({
            "/api/v1/info": (200, '{"nozzle_diameter": 0.4}'),
            "/api/printer": (200, '{"telemetry": {"material": "PLA"}}'),
        })
        actual = print_send.printer_actual("host", {"type": "prusalink"})
        self.assertEqual(actual, {"nozzle_diameter": 0.4, "material": "PLA"})

    def test_endpoint_failure_leaves_the_value_missing(self):
        self.fake_http({
            "/api/v1/info": (500, "boom"),
            "/api/printer": (200, '{"telemetry": {"material": "PLA"}}'),
        })
        actual = print_send.printer_actual("host", {"type": "prusalink"})
        self.assertEqual(actual, {"material": "PLA"})

    def test_non_prusalink_printers_report_nothing_yet(self):
        # Moonraker exposes the same facts under different keys; until that is
        # implemented the honest answer is "unknown", which surfaces as an
        # unverified note rather than a false all-clear.
        self.assertEqual(
            print_send.printer_actual("host", {"type": "moonraker"}), {})


if __name__ == "__main__":
    unittest.main()
